# -*- coding: utf-8 -*-
# Implementation of Select2Col.
# Author: Qian Huang <huangq@zhejianglab.com>, Yuntao Liu <liuyt@zhejianglab.com>
# License: TDG-Attribution-NonCommercial-NoDistribs

name: point_pillar_Select2Col
root_dir: external_paths/data_root
validate_dir: external_paths/data_root
test_dir: external_paths/data_root

wild_setting:
  seed: 20
  async: True
  async_mode: 'iosi'
  loc_err: False
  xyz_std: 0.3
  ryp_std: 0.2

yaml_parser: load_point_pillar_params
train_params:
  batch_size: &batch_size 4
  # batch_size: &batch_size 1
  epoches: &epoches 60
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 7

# To Align with heter setting
input_source: ['lidar']
label_type: lidar
comm_range: 200
fusion:
  args:
    clip_pc: false
    proj_first: false
  core_method: intermediatemulticlass
  dataset: v2xverse

preprocess:
  # Options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: SpVoxelPreprocessor
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: &voxel_size [0.4, 0.4, 36]
    # voxel_size: &voxel_size [0.125, 0.125, 36] # consider more detail
  cav_lidar_range: &cav_lidar [-115.2, -38.4, -22, 115.2, 38.4, 14] # change dimension to align with grid requirement
  # cav_lidar_range: &cav_lidar [ -140.8, -38.4, -3, 140.8, 38.4, 1 ]

data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]
- NAME: random_world_scaling
  WORLD_SCALE_RANGE: [0.95, 1.05]

postprocess:
  # core_method: 'VoxelPostprocessorSelect2Col'  # VoxelPostprocessor, BevPostprocessor supported
  core_method: VoxelPostprocessor  # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [ 0, 90 ]
    num: &achor_num 2
    feature_stride: 4
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.2
  gt_range: *cav_lidar # for evaluation
  order: 'hwl'  # hwl or lwh
  max_num: 100  # Maximum number of objects in a single frame. Use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# Model related
model:
  core_method: point_pillar_Select2Col
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    head_dim: 128
    # head_dim: 256
    max_cav: *max_cav
    compression: 0  # Compression rate
    backbone_fix: False
    # align with heter, seems just decoration now
    multi_class: true
    base_bev_backbone:
      layer_nums: &layer_nums [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: &num_filters [ 64, 128, 256]
      num_upsample_filter: [128, 128, 128]
      upsample_strides: [1, 2, 4]
      
    pillar_vfe:
      num_filters: [64]
      use_absolute_xyz: True
      use_norm: True
      with_distance: False
    point_pillar_scatter:
      num_features: 64
    
    shrink_header:
      dim: [128]
      # dim: [256]
      input_dim: 384  # 128 * 3
      kernal_size: [3]
      padding: [ 1 ]
      stride: [ 1 ]
      # stride: [ 2 ]
    HPHA_fusion:
      fully: False
      voxel_size: *voxel_size
      downsample_rate: 4
      in_channels: 256
      multi_scale: True
      layer_nums: *layer_nums
      num_filters: *num_filters
      sparse:
        round: 1
        threshold: 0.01
        gaussian_smooth:
          k_size: 5
          c_sigma: 1.0

loss:
  # since original loss func largely different from select2col
  core_method: point_pillar_loss_select2col
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 2e-4
  args:
    eps: 1e-10
    weight_decay: 1e-2

lr_scheduler:
  core_method: cosineannealwarm # step, multistep, exponential and cosineannealwarm support
  epoches: *epoches
  warmup_lr: 2e-5
  warmup_epoches: 10
  lr_min: 5e-6
